### ISSUE TITLE
10.0.0-Alpha-3 Causes Bartender Icon Size to Shrink

### ISSUE THREAD

**Issue by Dmeister406** [SFX-WoW/Masque#250] opened 2022-10-26 07:07 UTC
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

10.0.0-Alpha-3

### Description

When simply updating from Masque 9.2.7 to 10.0.0-Alpha-3 while running the retail client of wow (10.0.0), the size of Bartender bar icons shrinks noticeably using the Shadow 1 Masque. This ONLY affects Bartender as Aura Frames are not changed, as can be seen in the screenshot linked. Changing the size of Bartender icons/padding etc does not rectify the issue.

### Screenshots

https://iili.io/D8jkmb.jpg

**Comment by QustavR** [comment] 2022-10-26 13:57
This also happens with Elvui actionbars. I can still change icon size in elvui, but masque seems to put an extra size multiplier on all icon properties on actionbars; going from size 30 to 40 results in similar size to what it should be for me.

Does not seem to affect weakauras, other addons or buff icons on unitframes even though my masque skins are set globally and enabled on relevant elvui settings, so it's isolated to actionbars.

**Comment by StormFX** [comment] 2022-10-26 14:21
@QustavR Are you using the same skin?

**Comment by StormFX** [comment] 2022-10-26 14:32
We'll have to see if this something in Alpha-3 after I push the next build. This is BT4 using Caith. 9.2.7 on the left, PTR on the right.

![image](https://user-images.githubusercontent.com/1234928/198054006-fcf50b0d-3b3d-48ef-ad8f-bb252a033b71.png)

**Comment by QustavR** [comment] 2022-10-26 14:48
> 

I've tried all my installed masque skins, and the size difference is noticeable with all of them, and even when I tick the disable box. the size of actionbar icons returns to normal when I disable masque, so it's definately masque.

**Comment by QustavR** [comment] 2022-10-26 15:13
![kuva](https://user-images.githubusercontent.com/116735796/198064373-4e24fb25-727f-48aa-ac3e-2ba2a045caa1.png)
The 2 icons on the lower corners are weakaura icons and their size hasn't changed even with masque on. 

![kuva](https://user-images.githubusercontent.com/116735796/198064771-1c2b374e-6d88-4347-ab20-70a04f460253.png)
This is what it's like when I disable masque from addons and the actionbars just have default elvui. Until yesterday the weakaura icons were indistinguishable from the actionbar icons.

**Comment by QustavR** [comment] 2022-10-26 16:37
tried at UI scale of 1.0, there's still a difference when comparing masque loaded or not

**Comment by StormFX** [comment] 2022-10-26 16:45
Make sure your action bars are set to the proper scale in ElvUI. I just had to reset mine in BT4, due to them being set at 0.8 for some reason (I've always used 1.0).

**Comment by StormFX** [comment] 2022-10-26 16:58
For those using Bartender4, Nevcairiel added migration code to make action bars scale correctly in the transition to 10.0, as can be seen [here](https://github.com/Nevcairiel/Bartender4/commit/f513e91c69f0ff8f25a3277855ea97c2eaaaa75d). Therefore, you'll have to adjust your bars to your preferred scale.

**Comment by Uggers** [comment] 2022-10-26 20:21
Don't worry I know 100% this is a change that has to happen not trying to ask you to fix it for me

Just because I noted you mentioned using bartender too
How did you translate the scale/position/padding from 9.2.7 to 10.0.0

I can use the v9 off the addon and see all the settings, but when I update to v10.0 the settings are the same (obviously) so I can't figure out exactly what I need to adjust.

**Comment by Dmeister406** [comment] 2022-10-26 21:09
Oh I didn't realise that the base button dimensions were changed for DF! I'll have to go back and re-scale and reposition my bars. Thanks for clarifying!

**Comment by StormFX** [comment] 2022-10-26 22:15
@Uggers Sorry for the delay. You'll need to adjust your scale and padding. You can find out what they used to be by dividing the current value by 0.8. Eg, if your current scale value is 0.8, then 0.8/0.8 = 1.0.

**Comment by Uggers** [comment] 2022-10-26 22:17
> @Uggers Sorry for the delay. You'll need to adjust your scale and padding. You can find out what they used to be by dividing the current value by 0.8. Eg, if your current scale value is 0.8, then 0.8/0.8 = 1.0.

@StormFX  thats alright, appreciate you replying anyway. thank I'll give it a crack and see how it goes.

**Comment by sariouso** [comment] 2022-10-26 23:47
Experiencing this issue too. Bartender by itself is perfectly fine. It's just when enabling masque that the icons shrink in the bar. I tried changing scale and padding but it didn't fix anything.

**Comment by Dmeister406** [comment] 2022-10-26 23:49
> 

Yeah, I found that you have to /reload the UI once you have made changes to scale/padding in order for the changes to apply properly to the bars.

**Comment by sariouso** [comment] 2022-10-26 23:56
> Yeah, I found that you have to /reload the UI once you have made changes to scale/padding in order for the changes to apply properly to the bars.
That didn't change anything unfortunately.

**Comment by Nillx** [comment] 2022-10-27 00:24
I installed the new beta but  for some reason i cant see the options to select a skin 
![image](https://user-images.githubusercontent.com/34476875/198162760-9de67c30-53d7-4946-8711-bf253cf5e7ea.png)

Am i missing something?

**Comment by StormFX** [comment] 2022-10-27 01:00
Open Masque via the `/msq` chat command, go to General Settings/Interface and turn on the stand-alone GUI.

**Comment by kstange** [comment] 2022-10-27 08:34
I am using an outdated simple mod called MasqueBlizzBars that I adapted for the updated UI with Caith which applies the Masque theme to the built-in bars.  There's no scaling options or padding options available in the native UI to address this behavior, but I'm seeing the same behavior where the buttons are now tiny compared to how they were with Masque 9.2.7.

Both screenshots are from the 10.0.0 UI.

<img width="138" alt="image" src="https://user-images.githubusercontent.com/8593622/198233544-437a5e40-4643-4354-9c78-9793aae9cfc7.png">
<img width="144" alt="image" src="https://user-images.githubusercontent.com/8593622/198233689-3166bbbc-5426-4c8c-801d-6848cf451593.png">

**Comment by Thrayl** [comment] 2022-10-27 10:19
> @Uggers Sorry for the delay. You'll need to adjust your scale and padding. You can find out what they used to be by dividing the current value by 0.8. Eg, if your current scale value is 0.8, then 0.8/0.8 = 1.0.

This fix doesn't work because it doesn't reduce the padding. You can get the icon size to pre-DF but they will still be too far apart. Wouldn't a simpler fix for this to be set the scaling to 45 if using the default Blizz action bars or 36 if using an action bar addon? At least until the action bar addons update their code to support the higher scale..

**Comment by Nillx** [comment] 2022-10-27 11:11
Scaling the icons to 1.1 fixes the size issue for me but there is no way to adjust where the keybind is shown as of result it appears on the edge of the icon, same applies to the spell "stacks" number
![image](https://user-images.githubusercontent.com/34476875/198269374-2538c40a-45b3-428d-9a73-1b6728d37267.png)

**Comment by azuraji** [comment] 2022-10-27 11:19
> Scaling the icons to 1.1 fixes the size issue for me but there is no way to adjust where the keybind is shown as of result it appears on the edge of the icon, same applies to the spell "stacks" number ![image](https://user-images.githubusercontent.com/34476875/198269374-2538c40a-45b3-428d-9a73-1b6728d37267.png)

It's the specific skin that controls the position of the hotkey label. I had to adjust this manully inside the LUA files to make it look like before.

![image](https://user-images.githubusercontent.com/72912613/198270828-09caf160-ee12-4317-89c2-1b9c0ed71e8e.png)

**Comment by Nillx** [comment] 2022-10-27 11:59
Thanks, fixed that. Is there a way to make the macro text smaller?

**Comment by glassleo** [comment] 2022-10-27 12:06
Adjusting skins is not really a good solution, since you might want to use the same skin in multiple addons. For me the icons display properly in WeakAuras but in Bartender they look crazy with tiny icons and text all over the place.

**Comment by glassleo** [comment] 2022-10-27 12:18
> > Adjusting skins is not a good solution. Half the point of Masque is so you can have the same skin in multiple addons.
> 
> Different skins use different settings, it's been like that since the beginning. DF tweaked some of the factors and if you adjust the numbers proportionally to that then you should be fine.

What are you talking about. Bartender is displaying the skins completely differently from WeakAuras for example. Adjusting a skin won't fix that.

**Comment by glassleo** [comment] 2022-10-27 12:24
Masque 10.0.0-Beta:
![image](https://user-images.githubusercontent.com/9146240/198282911-962484b1-cc97-4ac8-890f-da84477cd0aa.png)

Masque 9.2.7:
![image](https://user-images.githubusercontent.com/9146240/198283254-bd2796d6-1872-446f-95ec-9cd604ca5f4e.png)

The buttons are Bartender4 except the bototm right which is WeakAuras.

**Comment by glassleo** [comment] 2022-10-27 13:41
> I still dont understand why is with Bartender 4.12.4 (10.0) and Masque 9.2.7 (it works but kind of bugged in 10.0) i dont need to re-configure anything.
> 
> And suddenly, with 4.12.4 (10.0) and Masque 10.0.0-Beta i need to change Bartender toolbar setting: set scale, set paddings, and move toolbars to fit vertical gaps... And i also need to manually tweak text coordinates in Masque skins. I thought that Masque is a button re-skin and not a re-size and re-position mod.
> 
> It looks like something is broken or too strict in the new version of Masque.
> 
> I mean if 9.2.7 can show me things like before then why Masque 10.0.0 is so different and makes everything complicated?

Yeah I don't understand all these changes either. My skins look great in 9.2.7 (just the options panel is broken). Why do we have to break every single skin once again?

Also I spent like 2 hours trying to update my skin with the new changes and I cannot for the life of me get the "Highlight" and "Pushed" textures to align properly on top of the "Normal" textue. They are always slightly off-center by about 1 pixel. This is not the case in 9.2.7. Even the new built in "Default" skin seems to have issues with the "Pushed" texture being about 1 pixel too far left and 1 pixel too high up.

**Comment by StormFX** [comment] 2022-10-27 15:29
> This fix doesn't work because it doesn't reduce the padding. You can get the icon size to pre-DF but they will still be too far apart.

The migration method added to Bartender4 adjusts the icon and padding, so you need to adjust them both. To find out what they were before the patch, simply take the post-patch value (if you haven't changed it) and divide it by 0.8.

> Wouldn't a simpler fix for this to be set the scaling to 45 if using the default Blizz action bars or 36 if using an action bar addon? At least until the action bar addons update their code to support the higher scale..

Action bar add-ons generally use either the default action buttons or a variation on the default button template, which are larger. Using a scaling factor of 36 on those buttons would cause the button and skin to no longer be on a 1:1 scale, causing even more problems.

As I mentioned, users will need to adjust the scale and padding of their action bars and then reposition them.

> Scaling the icons to 1.1 fixes the size issue for me but there is no way to adjust where the keybind is shown as of result it appears on the edge of the icon, same applies to the spell "stacks" number ![image](https://user-images.githubusercontent.com/34476875/198269374-2538c40a-45b3-428d-9a73-1b6728d37267.png)

None of my skins have been updated yet. That's an issue with the skin iteself.

> Thanks, fixed that. Is there a way to make the macro text smaller?

No. Mask doesn't control font sizes because font objects are generally a pain to work with. I may consider throwing together a plug-in later.

> I still dont understand why is with Bartender 4.12.4 (10.0) and Masque 9.2.7 (it works but kind of bugged in 10.0) i dont need to re-configure anything.

> Yeah I don't understand all these changes either. My skins look great in 9.2.7 (just the options panel is broken). Why do we have to break every single skin once again?

The reason for the changes is explained [above](https://github.com/SFX-WoW/Masque/issues/250#issuecomment-1292338786). You also need to keep in the mind that skins will need to be updated.

**Comment by TinyTrbl** [comment] 2022-10-27 16:13
> To clarify, Action buttons pre-Dragonflight were 36 x 36. In Dragonflight, they're 45 x 45
> so Masque has to account for the difference in scaling
> **has to account**

Basically to follow new default bigger buttons you went with some mostly unneeded changes and made thing more complicated for small skin devs and regular addon users.

The thing is that Masque got exactly zero problems with scaling on a very small or very big buttons/icon borders. I used it for years with 90x90 button with no issues. But after 10.0 you have decided that it is not good enough...

Please bear in mind that I don't want to offend you! It just turned out to be a strange thing - when following some arbitrary "standards" made everything worse.

**Comment by StormFX** [comment] 2022-10-27 17:07
The "standard" is action button size, since that's the majority of what Masque skins. But to explain the reasoning further:

Pre-Dragonflight, action buttons were 36 x 36. Thus, the scale factor was 36. Action buttons, at their default size, were at a scale of 1.0, meaning that skins would be exactly the dimensions specified by the skin author. Any scaling of the button would result in an appropriate adjustment to the skin.

In Dragonflight, action buttons were increased in size to 45 x 45. Therefore, in order to maintain a scale of 1.0 at the default size, the scale factor for those buttons had to be increased to 45. To demonstrate using Caith:

Caith's `Normal` texture (the "frame" around the icon) is 42 x 42. Using the current scaling method on an action button at its default size means that the texture will be 42 x 42, as specified by skin. However, if the scaling factor had been left at 36, the texture would be scaled to 52.5 x 52.5.

Enter Bartender4. With the update, a migration feature was added in BT to ensure that action bars stayed exactly the same as they were pre-Dragonflight. Action bars at a scale of 1.0 now have a scale of 0.8, meaning their _actual_ button sizes have been reduced to 36 x 36.

At first, this makes sense because doing the math, you end up with Caith's `Normal` texture back at 42 x 42 (`((45 / 36) * 0.8) *42 = 42`). The problem is that this migration feature is specific to Bartender4. Any add-on that _doesn't_ implement a similar feature will end up with skins 25% _larger_ than before.

While I can appreciate the frustration with having to reposition your action bars, it's not within Masque's scope to account for every single add-on's nuances. It _is_ just a library at its core, after all.

That all said, I may implement a "Use Classic Scaling" option that will cause Masque to use a scale factor of 36. It would be disabled by default so that users who've already adjusted their UIs won't be affected.

**Comment by StormFX** [comment] 2022-10-27 18:14
In the next build, I've added a "Classic Scaling" option that will cause Masque to scale skins using the old scale factor. This will be found in the `General Settings`/`Interface` panel and will be disabled by default (for the reasons I mentioned above. Additionally, I adjusted the type filter so that smaller action buttons (eg, pet, stance, possess) will not be affected by the new scaling at all.

**Comment by StormFX** [comment] 2022-10-27 21:07
Beta-2 is up, if you haven't already updated.

https://github.com/SFX-WoW/Masque/releases/tag/10.0.0-Beta-2

**Comment by Nillx** [comment] 2022-10-27 21:17
Getting errors with Beta-2

```
2x Interface/AddOns/Masque/Core/Regions/Regions.xml:9 Error loading Interface/AddOns/Masque/SlotIcon.lua

2x FrameXML\Bindings.xml:1 Interface/AddOns/Masque/Core/Regions/Regions.xml:9 Error loading Interface/AddOns/Masque/SlotIcon.lua
```

**Comment by StormFX** [comment] 2022-10-27 23:05
This is what happens when one codes while tired. >.< Give me a few.

**Comment by glassleo** [comment] 2022-10-27 23:07
> In the next build, I've added a "Classic Scaling" option that will cause Masque to scale skins using the old scale factor. This will be found in the `General Settings`/`Interface` panel and will be disabled by default (for the reasons I mentioned above).

Thank you so much for this compromise.

**Comment by Nillx** [comment] 2022-10-27 23:07
Its fine, take your rest!

**Comment by StormFX** [comment] 2022-10-27 23:11
Fixed in [Beta-3](https://github.com/SFX-WoW/Masque/releases/tag/10.0.0-Beta-3).

**Comment by StormFX** [comment] 2022-10-29 03:25
This should all be handled in 10.0.0. Thanks everyone for reporting!

**Closed by StormFX** 2022-10-29 03:25 UTC
Labels: ​Completed, ≡ ElvUI, ≡ Bartender4
