### ISSUE TITLE
Enhancement: Spell Alerts Don't Match Button Shape

### ISSUE THREAD

**Issue by Rackelhardt** [SFX-WoW/Masque#361] opened 2024-04-30 17:19 UTC
### Game Flavor

Retail

### Game Version

10.2.6

### Add-On Version

10.2.6

### Description

I didnt play WoW for like 14 months.
When i started the game yesterday i realized that they updated the Activation Border effect.
It looks more detailed now, but unfortunately it is no longer displayed round on round button skins (i.e. Masque: Raeli or Masque: Cirque). With the old effect, it was displayed round on those skins.

![ff](https://github.com/SFX-WoW/Masque/assets/76191859/877f355c-357c-470e-ae17-a09929cf927c)

The icons i am using are from the addon TellMeWhen. 
The Skin in this case is Masque: Raeli - Ring Edge.

I am not sure if this is a problem from Masque or TellMeWhen though.

**Comment by StormFX** [comment] 2024-04-30 17:43
Blizzard changed the animation API and I've yet to figure out a way to replace them. I'd recommend using a square skin.

**Comment by Rackelhardt** [comment] 2024-04-30 17:51
alright, thank you

**Comment by Rackelhardt** [comment] 2024-05-21 18:03
Can you say approximately whether and if so, when you will install the round activation border?
I would really like to use round icons again.

thx for your work.

**Comment by StormFX** [comment] 2024-05-22 01:44
No ETA currently. The new animations are a tricky situation that I'm still trying finding a work around for that won't taint everything.

**Comment by Rackelhardt** [comment] 2024-05-22 03:00
Could you add the old ones in the meantime or isn't that possible anymore?
Sry if thats a supid question ;D

**Comment by StormFX** [comment] 2024-05-22 03:31
That code isn't available in non-Classic anymore.

**Comment by StormFX** [comment] 2024-07-05 23:12
This issue should be addressed in the [latest beta](https://github.com/SFX-WoW/Masque/releases).

**Closed by StormFX** 2024-07-05 23:12 UTC
Labels: Enhancement, Completed

**Comment by Rackelhardt** [comment] 2024-07-07 20:41
Awesome!

**Comment by Rackelhardt** [comment] 2024-07-09 19:10
I installed the Beta and it still looks like on the picture i posted.
Do i have to wait until the dude who created the specific Masque skin implements it via update?
In my case Masque Raeli

**Comment by StormFX** [comment] 2024-07-09 19:43
Yeah. In the interim, if you're comfortable editing the skin, you can add the following at line `462` of `Masque_Raeli.lua`:

```lua
	SpellAlert = {
		Height = 29,
		Width = 29,
	},
```
So it should read like so:

```lua
	JunkIcon = { -- Line 448
		Atlas = "bags-junkcoin", -- Gold coin icon
		-- Color = {1, 1, 1, 1},
		BlendMode = "BLEND",
		DrawLayer = "OVERLAY",
		DrawLevel = 5,
		Width = 16,
		Height = 16,
		Point = "TOP",
		RelPoint = "TOP",
		OffsetX = 0,
		OffsetY = 1,
		-- SetAllPoints = nil,
	},
	SpellAlert = {
		Height = 29,
		Width = 29,
	},
}, true) -- Line 466
```

**Comment by Rackelhardt** [comment] 2024-07-09 20:47
Thx bro

**Comment by StormFX** [comment] 2024-07-09 20:54
I'm assuming it worked?

**Comment by Rackelhardt** [comment] 2024-07-09 22:16
No. Unfortunately, it didn't work :(

I did it like u said:
![image](https://github.com/SFX-WoW/Masque/assets/76191859/d0fe62ad-861c-4063-95b5-6a2a9e792ffb)

reloaded and restartet the game but that didnt help.

**Comment by StormFX** [comment] 2024-07-10 03:41
I'll see if I can get it working tomorrow and send you a copy of the file.

**Comment by StormFX** [comment] 2024-07-10 13:27
Literally all I did was add the lines I mentioned above. I also added a section for the square skin. So if it's not working for you, make sure you're on **Retail** and that you have Masque's latest beta installed.

![image](https://github.com/SFX-WoW/Masque/assets/1234928/25c71a56-3adf-44c3-89f2-5da736249946)
![image](https://github.com/SFX-WoW/Masque/assets/1234928/cbbf5f49-c065-4b20-bd78-13d52d06052d)

Here's the file I edited. Note that you'll need to take of the `.txt` and then replace your existing file.

[Masque_Raeli.lua.txt](https://github.com/user-attachments/files/16162744/Masque_Raeli.lua.txt)

**Comment by Rackelhardt** [comment] 2024-07-10 13:48
Ok i just realized that its not the problem of Masque Raeli but the Problem of TellMeWhen.
On my Action Bar (Bartender4) it works fine.

![image](https://github.com/SFX-WoW/Masque/assets/76191859/b6030530-8973-4f67-9e0f-6f2c553d13b7)

I guess i have to wait until TellMeWhen gets an Update.

Thank you though!

**Comment by StormFX** [comment] 2024-07-10 14:07
The Beta of Masque is, well, a beta, so add-ons probably won't update until after a full release. That said, Bartender 4 is still using the old style of spell alerts, which aren't what was added in Masque's beta. If you want to see the new animations, try using Dominos or Masque Blizzard Bars (reskins the default buttons, same as Dominos but without the extra stuff).

This is Serenity with the new animation:
https://github.com/SFX-WoW/Masque/assets/1234928/4cdd4267-8173-4a2f-b2d8-f70ba7c22de1

**Comment by Rackelhardt** [comment] 2024-07-10 14:29
Okay i just tested it with Masque Blizzard Bars and Raeli works. Nice.

But one question: Who actually designed the round activation border? Was it you?
And if so, is it possible that it is a bit more noticeable? So a bit brighter like the original from Blizzard or like the animation from Bartender4?
Actually, I don't think the design of Bartender and Blizzard is that bad, because it completely surrounds the icon with a glow and not a single spark wandering around it.
However, I find the border of Blizzard a bit too thick and too blatant. I think I like the one from Bartender4 best.

I hope I don't sound presumptuous.

It's just an idea.

P.S.
Do you have any idea how long it will take to release the full version? Just a very rough estimate. Days? Weeks?
In any case, thank you very much for your commitment!

**Comment by StormFX** [comment] 2024-07-10 15:58
I'm hoping to get a release out before the pre-patch (7/23). I created the textures for new animations. Making them "brighter" isn't really an option at the moment because creating them is a pain (I have to create each frame separately, and there's 30 frames for each shape). Bartender 4 uses the old style and the "circle" version is just one I manipulated to a round shape.

**Comment by Rackelhardt** [comment] 2024-07-10 17:25
Oh lol.
Then Thank you very much for the work!

**Comment by Rackelhardt** [comment] 2024-07-11 02:00
One thing I don't understand:
You said earlier that you couldn't use the old round design because the code isn't available anymore in non-classic.
But on the other hand Bartender seem to use the old design and it works.

Have I misunderstood something?

**Comment by StormFX** [comment] 2024-07-11 03:01
Bartender4 uses its own library that effectively duplicates the old-style purely in code. The only way I could reproduce the effect is to do the same thing, which I'd have to do since not everyone uses Bartender4. That would leave users with multiple copies of the same code, depending on which version of the game they're playing and which add-ons they're using. Frankly, it's a lot of extra work and overhead for a result that's dated and frankly, IMO, ugly. :P

**Comment by Rackelhardt** [comment] 2024-07-11 23:54
Understandable.

The only reason I prefer the "stronger" effects is because I only play competitive arena and the stronger effects are easier to see in the corner of my eye.
I could just go back to the square icons (I do that with my normal action bars too), but with the TMW icons loosely arranged around my character, it looks quite ugly when they're square.

But I think I'll get used to it.

**Comment by StormFX** [comment] 2024-07-12 01:01
I'll probably add a stronger effect later. I was playing around with some ideas that seemed to work.

**Comment by Rackelhardt** [comment] 2024-07-27 22:44
btw. i figured out the problem:

![image](https://github.com/user-attachments/assets/2ea8c671-45fe-4c76-962b-8d6c6433a97b)

Spell Alert Style was on "none" somehow.

**Comment by Rackelhardt** [comment] 2024-07-27 22:46
^Dude THANK you!

That was the problem!

**Comment by StormFX** [comment] 2024-07-27 23:16
It defaults to being set to "None" because some people don't like the custom animations.

**Comment by Rackelhardt** [comment] 2024-07-28 03:32
But its the only way to get the round animations, right?

**Comment by ascott18** [comment] 2024-07-28 03:42
It seemed to me that was the case. I found it confusing when updating TMW to support round animations that in order to make round animations be used at all I have to change this setting that's buried pretty deep.

**Comment by StormFX** [comment] 2024-07-28 10:43
> But its the only way to get the round animations, right?

Yes.

> It seemed to me that was the case. I found it confusing when updating TMW to support round animations that in order to make round animations be used at all I have to change this setting that's buried pretty deep.

The placement of the option is inline with the other animation options. I'll probably change the default setting to "Modern" since it's currently only available for Retail, but I needed to get everything working correctly before I fine-tuned things. And most people don't use non-square skins, so. :P
