### ISSUE TITLE
Bug: New 'Default' Skin not Affecting WeakAuras

### ISSUE THREAD

**Issue by therealdyrone17** [SFX-WoW/Masque#261] opened 2022-10-28 18:23 UTC
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

10.0.0-Beta-3

### Description

The addon is functioning correctly, just the new Default skin doesn't appear to have the border present on the new dragonflight actionbars. 

No feasible customizations are set, just trying to apply the Default skin at a global level. This is a fresh install of the game, the only other modifiers on icons is an icon pack: https://github.com/kodewdle/IconPacks 

### Screenshots

https://imgur.com/a/fcG0nOb

**Comment by StormFX** [comment] 2022-10-28 18:41
Try reloading or selecting a different skin then back to the Default.

**Comment by StormFX** [comment] 2022-10-28 19:22
So, the issue is that the default skins are based on the default UI of their respective clients. In all versions of the default UI, aura buttons don't get skinned. However, I'm going to add the ability of custom types (WeakAuras uses a custom type) to be skinned by the default skins.

**Comment by therealdyrone17** [comment] 2022-10-28 22:44
> So, the issue is that the default skins are based on the default UI of their respective clients. In all versions of the default UI, aura buttons don't get skinned. However, I'm going to add the ability of custom types (WeakAuras uses a custom type) to be skinned by the default skins.
good deal! thanks a ton. really like the new look of the base ui, trying to get my WA's to replicate. let me know if i can be of any help

**Comment by StormFX** [comment] 2022-10-29 02:57
The 10.0.0 release will remove the restrictions for the new _Default_ skin.

**Comment by StormFX** [comment] 2022-10-29 03:22
This should be fixed in 10,0,0.

**Closed by StormFX** 2022-10-29 03:22 UTC
Labels: ​Fixed, ≡ WeakAuras
