### ISSUE TITLE
Bug: Cannot Open Masque Config

### ISSUE THREAD

**Issue by ShadowSingularity** [SFX-WoW/Masque#255] opened 2022-10-27 20:01 UTC
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

9.2.7

### Description

/msq and the minimap button do not seem to work.

Going to to options > addons and opening it from there only shows what is on the screenshot.

### Error Message

```text
2x Interface/AddOns/Masque/Options/Core.lua:150: attempt to index upvalue 'InterfaceOptionsFrame' (a nil value)
[string "@Interface/AddOns/Masque/Options/Core.lua"]:150: in function `ToggleOptions'
[string "@Interface/AddOns/Masque/Masque.lua"]:120: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5219: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4919: in function <Interface/FrameXML/ChatFrame.lua:4915>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
self = <table> {
 SkinOptionsPanel = Frame {
 }
 SkinTexture = <function> defined @Interface/AddOns/Masque/Core/Regions/Texture.lua:39
 SetPulse = <function> defined @Interface/AddOns/Masque/Core/Regions/Frame.lua:191
 SkinText = <function> defined @Interface/AddOns/Masque/Core/Regions/Text.lua:32
 Skins = <table> {
 }
 AddSkin = <function> defined @Interface/AddOns/Masque/Skins/Skins.lua:48
 API_VERSION = 90002
 GetSize = <function> defined @Interface/AddOns/Masque/Core/Utility.lua:94
 GetRegion = <function> defined @Interface/AddOns/Masque/Core/Core.lua:26
 API = <table> {
 }
 Setup = <table> {
 }
 GetType = <function> defined @Interface/AddOns/Masque/Core/Core.lua:69
 RegTypes = <table> {
 }
 Authors = <table> {
 }
 SkinIconBorder = <function> defined @Interface/AddOns/Masque/Core/Regions/IconBorder.lua:72
 OLD_VERSION = 70200
 db = <table> {
 }
 Websites = <table> {
 }
 SkinMask = <function> defined @Interface/AddOns/Masque/Core/Regions/Mask.lua:33
 Options = <table> {
 }
 SetNormalColor = <function> defined @Interface/AddOns/Masque/Core/Regions/Normal.lua:194
 UpdateSpellAlert = <function> defined @Interface/AddOns/Masque/Core/Regions/SpellAlert.lua:43
 NoOp = <function> defined @Interface/AddOns/Masque/Core/Utility.lua:39
 ToggleDebug = <function> defined @Interface/AddOns/Masque/Masque.lua:153
 SetBackdropColor = <function> defined @Interface/AddOns/Masque/Core/Regions/Backdrop.lua:120
 SkinFrame = <function> defined @Interface/AddOns/Masque/Core/Regions/Frame.lua:58
 __Hidden = <table> {
 }
 SkinShadow = <function> defined @Interface/AddOns/Masque/Core/Regions/Shadow.lua:102
 GetID = <function> defined @Interface/AddOns/Masque/Core/Groups.lua:40
 OptionsLoaded = true
 Callback = <table> {
 }
 WOW_RETAIL = true
 Locale = <table> {
 }
 SkinIcon = <function> defined @Interface/AddOns/Masque/Core/Regions/Icon.lua:90
 SetCooldownColor = <function> defined @Interface/AddOns/Masque/Core/Regions/Frame.lua:180
 GetArg = <function> defined @Interface/AddOns/Masque/Options/Core.lua:186
 ToggleOptions = <function> defined @Interface/AddOns/Masque/Options/Core.lua:147
 Group_MT = <table> {
 }
 GetOptions = <function> defined @Interface/AddOns/Masque/Options/Skins.lua:160
 UpdateProfile = <function> defined @Interface/AddOns/Masque/Masque.lua:168
 UpdateSkinOptions = <function> defined @Interface/AddOns/Masque/Options/Skins.lua:478
 EmptyTypes = <table> {
 }
 SkinNormal = <function> defined @Interface/AddOns/Masque/Core/Regions/Normal.lua:111
 LDBO = <table> {
 }
 GetScale = <function> defined @Interface/AddOns/Masque/Core/Utility.lua:83
 ProfilesPanel = Frame {
 }
 LDBI = <table> {
 }
 OptionsPanel = Frame {
 }
 USE_LDS = true
 GetGroup = <function> defined @Interface/AddOns/Masque/Core/Groups.lua:89
 SkinButton = <function> defined @Interface/AddOns/Masque/Core/Button.lua:52
 SetTextureColor = <function> defined @Interface/AddOns/Masque/Core/Regions/Texture.lua:112
 SetShadowColor = <function> defined @Interface/AddOns/Masque/Core/Regions/Shadow.lua:90
 SetGlossColor = <function> defined @Interface/AddOns/Masque/Core/Regions/Gloss.lua:102
 SkinGloss = <function> defined @Interface/AddOns/Masque/Core/Regions/Gloss.lua:90
 Groups = <table> {
 }
 SkinBackdrop = <function> defined @Interface/AddOns/Masque/Core/Regions/Backdrop.lua:138
 GetColor = <function> defined @Interface/AddOns/Masque/Core/Utility.lua:26
 SkinNewItem = <function> defined @Interface/AddOns/Masque/Core/Regions/NewItem.lua:73
 GetStandAlone = <function> defined @Interface/AddOns/Masque/Options/Core.lua:181
 CRLF = "
 "
 GetTexCoords = <function> defined @Interface/AddOns/Masque/Core/Utility.lua:105
 CleanDB = <function> defined @Interface/AddOns/Masque/Core/Groups.lua:103
 Version = "9.2.7"
 SkinCooldown = <function> defined @Interface/AddOns/Masque/Core/Regions/Frame.lua:106
 WOW_VERSION = 100000
 SkinQuestBorder = <function> defined @Interface/AddOns/Masque/Core/Regions/QuestBorder.lua:73
 SkinList = <table> {
 }
 UpdateNormal = <function> defined @Interface/AddOns/Masque/Core/Regions/Normal.lua:52
 SetPoints = <function> defined @Interface/AddOns/Masque/Co
```

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/17858076/198386741-82ee8461-7116-4568-b77d-40518a5f3429.jpg)

**Comment by StormFX** [comment] 2022-10-27 20:22
Masque 9.2.7 is not compatible with Dragonflight. Grab the latest Beta. Though I'll be releasing another beta shortly, so you may hold off until Beta-2 is available.

https://github.com/SFX-WoW/Masque/releases

**Comment by StormFX** [comment] 2022-10-27 20:54
Duplicate of #251.

**Closed by StormFX** 2022-10-27 20:54 UTC
Labels: Duplicate, Unrelated
